### ISSUE TITLE
Publish Bottlerocket ECS Updater Image to ECR public and update updater stack

### ISSUE THREAD

**Issue by srgothi92** [bottlerocket-os/bottlerocket-ecs-updater#21]
**What I'd like:**
For development purpose we have configured updater image as parameter in updater stack so that we can provide our personal image. Before release we should publish final updater image to ECR public so customers can pull it directly. We should also update the updater stack with ECR public updater image location.

Implementation Suggestion:
One option is to keep the existing `UpdaterImage` parameter and pass ECR public location as default.
Other option is to delete the `UpdaterImage` parameter and update TaskDefinition to use ECR public location.

**Comment by samuelkarp** [comment]
This is done.
